<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'FEEDBACK_FORM_ATTR_BODY' => 'Сообщение',
    'FEEDBACK_FORM_ATTR_EMAIL' => 'E-mail',
    'FEEDBACK_FORM_ATTR_NAME' => 'ФИО',
    'FEEDBACK_FORM_ATTR_SUBJECT' => 'Тема',
    'FEEDBACK_FORM_ATTR_VERIFY_CODE' => 'Код верификации',
    'FEEDBACK_FLASH_SUCCESS_MSG' => 'Сообщение было успешно отправлено. Спасибо!',
    'FEEDBACK_FORM_INFO' => 'Если у вас есть вопросы или пожелания, вы можете написать нам сообщение. Спасибо!',
    'FEEDBACK_SUBMIT_BTN' => 'Отправить',
    'FEEDBACK_TITLE' => 'Контакты',
];
