<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'FEEDBACK_FORM_ATTR_BODY' => 'Message',
    'FEEDBACK_FORM_ATTR_EMAIL' => 'E-mail',
    'FEEDBACK_FORM_ATTR_NAME' => 'Full Name',
    'FEEDBACK_FORM_ATTR_SUBJECT' => 'Subject',
    'FEEDBACK_FORM_ATTR_VERIFY_CODE' => 'Verify Code',
    'FEEDBACK_FLASH_SUCCESS_MSG' => 'Message was successfully sent. Thank you!',
    'FEEDBACK_FORM_INFO' => 'If you have questions or deals you can write us a message. Thanks!',
    'FEEDBACK_SUBMIT_BTN' => 'Send',
    'FEEDBACK_TITLE' => 'Contacts',
];
